'use strict';
const express=require('express');const axios=require('axios');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const app=express();const PORT=Number(process.env.PORT||10000);const LIVE=String(process.env.LIVE_TRADING||'false').toLowerCase()==='true';const BASE_URL=String(process.env.OKX_BASE_URL||'https://www.okx.com').replace(/\/$/,'');const KEY=String(process.env.OK_ACCESS_KEY||'').trim();const SECRET=String(process.env.OK_ACCESS_SECRET||'').trim();const PASS=String(process.env.OKX_PASSPHRASE||'').trim();const TG_TOKEN=String(process.env.TELEGRAM_BOT_TOKEN||'').trim().replace(/["']/g,'');const TG_CHAT=String(process.env.TELEGRAM_CHAT_ID||'').trim();
const LOOP=Math.max(10000,Number(process.env.CHECK_INTERVAL||15000)),POS_LOOP=Math.max(3000,Number(process.env.POSITION_CHECK_INTERVAL||5000));const START=20,MINP=.75,MINPX=.25,MAXPX=.40,HALF=.5,MAXLOSS=3,COOLDOWN=1800000,DAILY=.10;const TP=Number(process.env.EARLY_TP_PCT||.30),SL=Number(process.env.EARLY_SL_PCT||.25);const STATE=process.env.BOT_STATE_FILE||path.join(__dirname,'bot-state.json');const ASSETS=['BTC','ETH','SOL'];const UNDER={BTC:'BTC-USDT-SWAP',ETH:'ETH-USDT-SWAP',SOL:'SOL-USDT-SWAP'};
const log=(x,v)=>console.log(v===undefined?x:x+' '+(typeof v==='string'?v:JSON.stringify(v)));const sleep=ms=>new Promise(r=>setTimeout(r,ms));const query=o=>Object.entries(o).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v)).join('&');
async function http(c){let e;for(let n=0;n<3;n++){try{return await axios({timeout:15000,...c});}catch(x){e=x;if(n<2)await sleep(400*(n+1));}}throw e;}
async function pub(ep,p={}){const s=query(p),r=await http({method:'GET',url:BASE_URL+ep+(s?'?'+s:'')});if(!r.data||String(r.data.code)!=='0')throw Error('OKX public '+r.status+': '+JSON.stringify(r.data));return Array.isArray(r.data.data)?r.data.data:[];}
function sig(ts,m,r,b){return crypto.createHmac('sha256',SECRET).update(ts+m.toUpperCase()+r+b).digest('base64');}
async function priv(m,r,obj){if(!KEY||!SECRET||!PASS)throw Error('OKX credentials missing');const ts=new Date().toISOString(),b=obj?JSON.stringify(obj):'',h={'OK-ACCESS-KEY':KEY,'OK-ACCESS-SIGN':sig(ts,m,r,b),'OK-ACCESS-TIMESTAMP':ts,'OK-ACCESS-PASSPHRASE':PASS,'Content-Type':'application/json'},x=await http({method:m,url:BASE_URL+r,data:b||undefined,headers:h});if(!x.data||String(x.data.code)!=='0')throw Error('OKX private '+x.status+': '+JSON.stringify(x.data));return Array.isArray(x.data.data)?x.data.data:[];}
function fresh(){return{day:new Date().toISOString().slice(0,10),paperEquity:START,realizedPnl:0,consecutiveLosses:0,cooldownUntil:0,halted:false,position:null,usedEvents:[],trades:[]};}
function load(){try{if(!fs.existsSync(STATE))return fresh();const s=JSON.parse(fs.readFileSync(STATE,'utf8'));return{...fresh(),...s,usedEvents:Array.isArray(s.usedEvents)?s.usedEvents:[],trades:Array.isArray(s.trades)?s.trades:[]};}catch(e){return fresh();}}const state=load();
function save(){try{const t=STATE+'.tmp';fs.writeFileSync(t,JSON.stringify(state,null,2));fs.renameSync(t,STATE);}catch(e){console.error('[STATE]',e.message);}}
function recalc(){let p=0,l=0;for(const t of state.trades)p+=Number(t.pnl||0);for(let i=state.trades.length-1;i>=0;i--){const x=Number(state.trades[i].pnl||0);if(x<0)l++;else if(x>0)break;}state.realizedPnl=Number(p.toFixed(4));state.consecutiveLosses=l;if(!LIVE)state.paperEquity=Number(Math.max(0,START+state.realizedPnl).toFixed(4));}
function blocked(){recalc();const n=Date.now();if(state.cooldownUntil){if(n<state.cooldownUntil){state.halted=true;return true;}state.cooldownUntil=0;state.consecutiveLosses=0;}if(state.consecutiveLosses>=MAXLOSS){state.cooldownUntil=n+COOLDOWN;state.halted=true;save();return true;}if(state.realizedPnl<=-(START*DAILY)){state.halted=true;save();return true;}state.halted=false;return false;}
const used=id=>state.usedEvents.includes(id);function mark(id){if(!used(id)){state.usedEvents.push(id);if(state.usedEvents.length>2000)state.usedEvents=state.usedEvents.slice(-2000);save();}}
function confirmed(a){return a.slice().sort((x,y)=>Number(x[0])-Number(y[0])).filter(x=>String(x[8])==='1');}async function candles(id,bar,limit=100){return confirmed(await pub('/api/v5/market/candles',{instId:id,bar,limit}));}async function ticker(id){return(await pub('/api/v5/market/ticker',{instId:id,instType:'EVENTS'}))[0]||null;}
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0;}function sd(a,m){return a.length<2?1e-8:Math.max(Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length),1e-8);}function pdf(x,m,s){const d=Math.max(s,1e-8),z=(x-m)/d;return Math.exp(-.5*z*z)/(d*Math.sqrt(2*Math.PI));}
// Bayesian model for one timeframe: returns -> P(UP|recent return).
function bayes(rows,min=25){const p=rows.map(x=>Number(x[4])).filter(Number.isFinite);if(p.length<min)return null;const r=[];for(let i=1;i<p.length;i++)if(p[i]>0&&p[i-1]>0)r.push(Math.log(p[i]/p[i-1]));if(r.length<20)return null;const up=r.filter(x=>x>0),dn=r.filter(x=>x<=0);if(!up.length||!dn.length)return null;const prior=(up.length+1)/(r.length+2),x=r[r.length-1],muU=mean(up),muD=mean(dn),sU=sd(up,muU),sD=sd(dn,muD),lu=pdf(x,muU,sU),ld=pdf(x,muD,sD),den=lu*prior+ld*(1-prior),pU=den>0?lu*prior/den:prior;return{direction:pU>=.5?'UP':'DOWN',pUp:pU,probability:pU>=.5?pU:1-pU,evidence:x};}
const bayes1H=r=>bayes(r,25),bayes15M=r=>bayes(r,30),bayes5M=r=>bayes(r,30);function logit(p){p=Math.min(.999999,Math.max(.000001,p));return Math.log(p/(1-p));}function sigmoid(x){return 1/(1+Math.exp(-x));}
// 1H is the direction gate. 5M and 15M are independent Bayesian confirmations.
// Final probability is a log-odds fusion: 50% weight 1H, 25% 15M, 25% 5M.
function fuse(h1,h15,h5){if(!h1||!h15||!h5)return null;const u=sigmoid(.50*logit(h1.pUp)+.25*logit(h15.pUp)+.25*logit(h5.pUp));return{direction:h1.direction,pUp:u,probability:h1.direction==='UP'?u:1-u,oneH:h1,fifteenM:h15,fiveM:h5};}
function asset(i){const s=((i.instId||'')+' '+(i.seriesId||'')+' '+(i.baseCcy||'')).toUpperCase();return ASSETS.find(a=>s.includes(a))||null;}function duration(i){const s=((i.instId||'')+' '+(i.seriesId||'')).toUpperCase();return s.includes('5MIN')?5:s.includes('15MIN')?15:null;}function updown(i){return((i.instId||'')+' '+(i.seriesId||'')).toUpperCase().includes('UPDOWN');}
function expiry(i){for(const k of ['expTime','expiryTime','endTime']){const n=Number(i[k]);if(Number.isFinite(n)&&n>0)return n;}const m=String(i.instId||'').match(/-(\d{6})-(\d{4})-(\d{4})$/);return m?Date.UTC(2000+Number(m[1].slice(0,2)),Number(m[1].slice(2,4))-1,Number(m[1].slice(4,6)),Number(m[3].slice(0,2)),Number(m[3].slice(2,4))):NaN;}function mins(i){const e=expiry(i);return Number.isFinite(e)?(e-Date.now())/60000:NaN;}function priceOK(x){return Number.isFinite(x)&&x>=MINPX&&x<=MAXPX;}function roundPx(x,t){t=Number(t);if(!(t>0))return Number(x.toFixed(6));const d=Math.max(0,(String(t).split('.')[1]||'').length);return Number((Math.round(x/t)*t).toFixed(d));}
// Half-Kelly for binary price c: b=(1-c)/c, f*= (bp-q)/b, then 50% of f*.
function halfKelly(p,c){if(!(p>c&&c>0&&c<1))return 0;const b=(1-c)/c,q=1-p;return Math.max(0,HALF*((b*p-q)/b));}function sizing(bank,p,c){const f=halfKelly(p,c),raw=Math.max(0,bank||0)*f;return{bankroll:bank,halfKelly:f,rawStake:raw,stake:Math.max(0,Math.min(bank,Math.floor(raw*100)/100))};}function orderSize(stake,price,i){const lot=Math.max(Number(i.lotSz||.1),.1),min=Math.max(Number(i.minSz||lot),lot);let z=Math.floor(stake/price/lot)*lot;if(z<min)z=min;return Number(z.toFixed(8));}
function series(){const x=String(process.env.EVENT_SERIES||'').split(',').map(s=>s.trim()).filter(Boolean);return x.length?x:ASSETS.flatMap(a=>[`${a}-UPDOWN-5MIN`,`${a}-UPDOWN-15MIN`]);}async function discover(){const out=[];for(const s of series()){try{for(const i of await pub('/api/v5/public/instruments',{instType:'EVENTS',seriesId:s}))out.push({...i,seriesId:i.seriesId||s});}catch(e){console.error('[DISCOVERY]',s,e.message);}}return out;}
async function scan(){const all=await discover(),f=all.filter(i=>asset(i)&&updown(i)&&[5,15].includes(duration(i))&&(!i.state||String(i.state).toLowerCase()==='live')&&!used(i.instId)&&mins(i)>=2&&mins(i)<=20);log('[SCAN]',{instruments:all.length,filtered:f.length});const cache={},out=[];for(const i of f){try{const a=asset(i);if(!cache[a])cache[a]={h1:await candles(UNDER[a],'1H',100),m15:await candles(UNDER[a],'15m',100),m5:await candles(UNDER[a],'5m',100)};const h1=bayes1H(cache[a].h1),h15=bayes15M(cache[a].m15),h5=bayes5M(cache[a].m5);if(!h1||!h15||!h5)continue;/* 1H establishes direction; both event timeframes must agree. */if(h1.direction!==h15.direction||h1.direction!==h5.direction)continue;const m=fuse(h1,h15,h5);if(!m||m.probability<MINP)continue;const t=await ticker(i.instId),ask=Number(t?.askPx||t?.last),bid=Number(t?.bidPx||t?.last);if(!(ask>0&&ask<1&&bid>0&&bid<1))continue;const side=m.direction==='UP'?'yes':'no',entry=side==='yes'?ask:1-bid;if(!priceOK(entry))continue;const ev=m.probability/entry-1;if(!(ev>0))continue;const sz=sizing(state.paperEquity,m.probability,entry);if(sz.stake<.01)continue;const c={inst:i,asset:a,duration:duration(i),side,entry,ev,model:m,sizing:sz,mins:mins(i)};out.push(c);log('[EVENT PASS]',{instId:i.instId,duration:c.duration,side,entryPx:Number(entry.toFixed(4)),oneH:Number((h1.probability*100).toFixed(1)),fiveM:Number((h5.probability*100).toFixed(1)),fifteenM:Number((h15.probability*100).toFixed(1)),finalBayesian:Number((m.probability*100).toFixed(1)),EV:Number((ev*100).toFixed(1)),halfKelly:Number((sz.halfKelly*100).toFixed(2)),stake:sz.stake});}catch(e){console.error('[CANDIDATE]',i.instId,e.message);}}return out.sort((a,b)=>b.ev-a.ev||b.model.probability-a.model.probability);}
async function getOrder(id,oid){return(await priv('GET','/api/v5/trade/order?'+query({instId:id,ordId:oid})))[0]||null;}async function place(c){const i=c.inst,px=roundPx(c.entry,Number(i.tickSz||.001)),sz=orderSize(c.sizing.stake,px,i),actual=Number((px*sz).toFixed(6));log('[ORDER SIZE]',{bankroll:c.sizing.bankroll,probability:c.model.probability,entryPx:px,halfKelly:c.sizing.halfKelly,targetStake:c.sizing.stake,contracts:sz,actualStake:actual});if(!LIVE)return{avgPx:px,accFillSz:sz,ordId:'PAPER-'+Date.now()};const body={instId:i.instId,tdMode:'isolated',side:'buy',ordType:'ioc',px:px.toFixed(6),sz:String(sz),outcome:c.side,ccy:'USDT',clOrdId:`evt${Date.now().toString(36)}`.slice(0,32)},r=(await priv('POST','/api/v5/trade/order',body))[0];if(!r||String(r.sCode)!=='0'||!r.ordId)throw Error('Order rejected: '+JSON.stringify(r));await sleep(500);return{...r,...(await getOrder(i.instId,r.ordId))};}
function pnl(side,entry,exit,size){return Number(((side==='yes'?exit-entry:entry-exit)*size).toFixed(4));}async function closePos(p,exit,reason){const i=p.inst,px=roundPx(exit,Number(i.tickSz||.001));let r;if(!LIVE)r={avgPx:px};else{const b={instId:i.instId,tdMode:'isolated',side:'sell',ordType:'ioc',px:px.toFixed(6),sz:String(p.size),outcome:p.side,ccy:'USDT',clOrdId:`exit${Date.now().toString(36)}`.slice(0,32)};r=(await priv('POST','/api/v5/trade/order',b))[0];if(!r||String(r.sCode)!=='0')throw Error('Exit rejected: '+JSON.stringify(r));}const ex=Number(r.avgPx||r.fillPx||px),profit=pnl(p.side,p.entryPx,ex,p.size);state.trades.push({at:new Date().toISOString(),instId:i.instId,side:p.side,entryPx:p.entryPx,exitPx:ex,size:p.size,pnl:profit,reason,probability:p.probability,ev:p.ev,stake:p.stake,halfKelly:p.halfKelly,duration:p.duration});state.position=null;recalc();if(state.consecutiveLosses>=MAXLOSS)state.cooldownUntil=Date.now()+COOLDOWN;save();await notify(`${profit>=0?'🟢':'🔴'} EVENT EXIT\n${i.instId}\n${p.side.toUpperCase()}\nEntry ${p.entryPx.toFixed(4)}\nExit ${ex.toFixed(4)}\nStake ${p.stake.toFixed(2)}U\nPnL ${profit>=0?'+':''}${profit.toFixed(4)}U\n${reason}\n${LIVE?'LIVE':'PAPER'}`);}
async function manage(){const p=state.position;if(!p)return;try{const t=await ticker(p.inst.instId),bid=Number(t?.bidPx||t?.last),ask=Number(t?.askPx||t?.last);if(!(bid>0&&bid<1))return;const cur=p.side==='yes'?bid:1-(ask>0?ask:bid),chg=(cur-p.entryPx)/p.entryPx;if(chg>=TP)return closePos(p,cur,'TP');if(chg<=-SL)return closePos(p,cur,'SL');}catch(e){console.error('[POSITION]',e.message);}}
async function notify(text){if(!TG_TOKEN||!TG_CHAT)return;try{await axios.post(`https://api.telegram.org/bot${TG_TOKEN}/sendMessage`,{chat_id:TG_CHAT,text});}catch(e){console.error('[TELEGRAM]',e.response?.data||e.message);}}
function entryMsg(c,fill,size){return['🟡 EVENT ENTRY',c.inst.instId,c.side.toUpperCase(),`Duration ${c.duration}M`,`Entry ${fill.toFixed(4)}`,`Contracts ${size}`,`Stake ${c.sizing.stake.toFixed(2)}U`,`1H Direction ${c.model.direction}`,`5M Bayesian ${(c.model.fiveM.probability*100).toFixed(1)}%`,`15M Bayesian ${(c.model.fifteenM.probability*100).toFixed(1)}%`,`Final Bayesian ${(c.model.probability*100).toFixed(1)}%`,`EV ${(c.ev*100).toFixed(1)}%`,`Half-Kelly ${(c.sizing.halfKelly*100).toFixed(2)}%`,`Expiry ${c.mins.toFixed(1)}m`,LIVE?'LIVE':'PAPER'].join('\n');}
async function trade(c){if(blocked()||state.position)return;mark(c.inst.instId);const r=await place(c),fill=Number(r.avgPx||r.fillPx||c.entry),size=Number(r.accFillSz||r.fillSz||orderSize(c.sizing.stake,fill,c.inst));if(!(size>0))throw Error('zero fill');state.position={inst:c.inst,side:c.side,entryPx:fill,size,openedAt:Date.now(),probability:c.model.probability,ev:c.ev,stake:c.sizing.stake,halfKelly:c.sizing.halfKelly,duration:c.duration};save();await notify(entryMsg(c,fill,size));}
let busy=false,started=false,loopTimer=null,posTimer=null;async function mainLoop(){if(busy){log('[LOOP]','duplicate invocation blocked');return;}busy=true;try{log('[HEARTBEAT]',new Date().toISOString());if(blocked()||state.position)return;const c=await scan();log('[SCAN RESULT]','candidates='+c.length);if(c.length)await trade(c[0]);}catch(e){console.error('[MAIN LOOP]',e.stack||e.message||e);}finally{busy=false;}}
function stats(){recalc();const w=state.trades.filter(t=>Number(t.pnl)>0).length,l=state.trades.filter(t=>Number(t.pnl)<0).length;return`📊 PAPER 統計\n\n交易筆數：${state.trades.length}\n勝場：${w}\n敗場：${l}\n勝率：${state.trades.length?(w/state.trades.length*100).toFixed(1):'0.0'}%\n累計 PnL：${state.realizedPnl>=0?'+':''}${state.realizedPnl.toFixed(4)}U\n目前資金：${state.paperEquity.toFixed(4)}U\n連敗：${state.consecutiveLosses}\n策略：1H Bayesian → 5M Bayesian + 15M Bayesian → Final Probability → EV → Half-Kelly`;}
function start(){if(started)return;started=true;log('[START]',`mode=${LIVE?'LIVE':'PAPER'} strategy=1H-BAYESIAN-FUSED events=5M/15M sizing=HALF-KELLY`);log('[SAFETY]',`1H direction + 5M/15M Bayesian agreement | P>=${MINP*100}% EV>0 Entry=${MINPX}-${MAXPX} 3-loss-cooldown=30m`);app.get('/',(_,r)=>r.json({ok:true,mode:LIVE?'LIVE':'PAPER',strategy:'1H-BAYESIAN-FUSED',formula:'1H Bayesian -> 5M Bayesian + 15M Bayesian -> final probability -> EV -> Half-Kelly',events:['5M','15M'],trades:state.trades.length,balance:state.paperEquity}));app.get('/health',(_,r)=>r.json({ok:true,mode:LIVE?'LIVE':'PAPER',strategy:'1H-BAYESIAN-FUSED',events:['5M','15M'],position:Boolean(state.position),trades:state.trades.length,balance:state.paperEquity}));app.listen(PORT,()=>log('[HTTP]','listening on '+PORT));void mainLoop();loopTimer=setInterval(()=>void mainLoop(),LOOP);posTimer=setInterval(()=>void manage(),POS_LOOP);}
process.on('SIGTERM',()=>{if(loopTimer)clearInterval(loopTimer);if(posTimer)clearInterval(posTimer);process.exit(0);});process.on('SIGINT',()=>{if(loopTimer)clearInterval(loopTimer);if(posTimer)clearInterval(posTimer);process.exit(0);});start();