'use strict';
const {TTLCache}=require('./cache');const okx=require('./okx');const config=require('./config');const db=require('./db');const {normalizeCandle,normalizeTicker,normalizeTrade,normalizeOrderBook,numberOrNull}=require('./normalize');const {pctChange,cvdDelta,stats,classifyStructure}=require('./analytics');
const cache=new TTLCache();
function isUsdtSwap(i){return i.instType==='SWAP'&&i.state==='live'&&(i.quoteCcy==='USDT'||i.settleCcy==='USDT');}
async function instruments(){const hit=cache.get('instruments');if(hit)return hit;const data=(await okx.getInstruments()).filter(isUsdtSwap);if(db.isReady())await db.upsertInstruments(data);return cache.set('instruments',data,config.CACHE_TTL_MS.instruments);}
async function tickers(){const hit=cache.get('tickers');if(hit)return hit;const allowed=new Set((await instruments()).map(x=>x.instId));return cache.set('tickers',(await okx.getTickers()).filter(x=>allowed.has(x.instId)).map(normalizeTicker),config.CACHE_TTL_MS.tickers);}
async function candles(instId,bar='5m'){if(!config.BARS.includes(bar))throw new Error('Unsupported bar');if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM ts)*1000 timestamp,open,high,low,close,volume,volume_currency "volumeCurrency",volume_quote "volumeQuote",confirmed FROM candles WHERE inst_id=$1 AND bar='5m' ORDER BY ts DESC LIMIT 500`,[instId]);let rows=r.rows.reverse();if(bar!=='5m'){const mins=bar==='15m'?15:bar==='1H'?60:240;const bucketMs=mins*60000;const m=new Map();for(const x of rows){const k=Math.floor(Number(x.timestamp)/bucketMs)*bucketMs;const a=m.get(k)||{timestamp:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:0,volumeCurrency:0,volumeQuote:0,confirmed:true};a.high=Math.max(Number(a.high),Number(x.high));a.low=Math.min(Number(a.low),Number(x.low));a.close=x.close;a.volume+=Number(x.volume||0);a.volumeCurrency+=Number(x.volumeCurrency||0);a.volumeQuote+=Number(x.volumeQuote||0);a.confirmed=a.confirmed&&Boolean(x.confirmed);m.set(k,a);}rows=[...m.values()];}return rows;}return (await okx.getCandles(instId,bar)).map(x=>normalizeCandle(x));}
async function trades(instId,limit=100){if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM ts)*1000 timestamp,price,size,side,trade_id "tradeId",source FROM trades WHERE inst_id=$1 ORDER BY ts DESC LIMIT $2`,[instId,limit]);return r.rows.reverse();}return (await okx.getTrades(instId,limit)).map(normalizeTrade);}
async function orderBook(instId,sz=config.MAX_ORDER_BOOK_LEVELS){const key=`orderbook:${instId}:${sz}`;const hit=cache.get(key);if(hit)return hit;const raw=(await okx.getOrderBook(instId,sz))[0];if(!raw)return null;const bids=raw.bids.map(normalizeOrderBook),asks=raw.asks.map(normalizeOrderBook);const bidVolume=bids.reduce((a,x)=>a+(x.volume||0),0),askVolume=asks.reduce((a,x)=>a+(x.volume||0),0),bestBid=bids[0]?.price??null,bestAsk=asks[0]?.price??null,total=bidVolume+askVolume;return cache.set(key,{symbol:instId,bids,asks,bestBid,bestAsk,bidVolume,askVolume,bidAskRatio:askVolume?bidVolume/askVolume:null,depthImbalance:total?(bidVolume-askVolume)/total:null,spread:bestBid!=null&&bestAsk!=null?bestAsk-bestBid:null,timestamp:numberOrNull(raw.ts),seqId:raw.seqId},config.CACHE_TTL_MS.orderBook);}
async function funding(instId){if(db.isReady()){const r=await db.query(`SELECT funding_rate "fundingRate",EXTRACT(EPOCH FROM funding_time)*1000 "fundingTime",EXTRACT(EPOCH FROM next_funding_time)*1000 "nextFundingTime",EXTRACT(EPOCH FROM ts)*1000 timestamp FROM funding_snapshots WHERE inst_id=$1 ORDER BY ts DESC LIMIT 1`,[instId]);if(r.rows[0])return {...r.rows[0],symbol:instId};}const d=(await okx.getFundingRate(instId))[0]||null;return d?{symbol:instId,fundingRate:numberOrNull(d.fundingRate),fundingTime:numberOrNull(d.fundingTime),nextFundingTime:numberOrNull(d.nextFundingTime),timestamp:numberOrNull(d.ts)}:null;}
async function fundingHistory(instId,limit=100){if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM funding_time)*1000 "fundingTime",funding_rate "fundingRate",realized_rate "realizedRate" FROM funding_history WHERE inst_id=$1 ORDER BY funding_time DESC LIMIT $2`,[instId,limit]);return r.rows.reverse();}return (await okx.getFundingHistory(instId,limit)).map(x=>({symbol:instId,fundingRate:numberOrNull(x.fundingRate),fundingTime:numberOrNull(x.fundingTime),realizedRate:numberOrNull(x.realizedRate),timestamp:numberOrNull(x.ts)}));}
async function oi(instId){if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM ts)*1000 timestamp,oi,oi_ccy "oiCcy",oi_usd "oiUsd" FROM open_interest_snapshots WHERE inst_id=$1 ORDER BY ts DESC LIMIT 500`,[instId]);const rows=r.rows.reverse();const now=Date.now();const at=age=>rows.slice().reverse().find(x=>Number(x.timestamp)<=now-age);const cur=rows.at(-1)||null;const changes={};for(const [k,ms] of Object.entries({'5m':300000,'15m':900000,'1h':3600000,'4h':14400000,'24h':86400000})){const b=at(ms);changes[k]=cur&&b&&Number(b.oiUsd)!==0?{value:Number(cur.oiUsd)-Number(b.oiUsd),pct:pctChange(Number(cur.oiUsd),Number(b.oiUsd)),sampledAt:b.timestamp}:{value:null,pct:null,sampledAt:null};}return {symbol:instId,current:cur,changes,sampleCount:rows.length};}const data=await okx.getOpenInterest();const x=data.find(v=>v.instId===instId);return x?{symbol:instId,current:{timestamp:numberOrNull(x.ts),oi:numberOrNull(x.oi),oiCcy:numberOrNull(x.oiCcy),oiUsd:numberOrNull(x.oiUsd)},changes:{'5m':null,'15m':null,'1h':null,'4h':null,'24h':null},sampleCount:1}:null;}
async function cvd(instId){if(!db.isReady())return {status:'資料不足',reason:'PostgreSQL 未啟用'};const windows={'5m':300000,'15m':900000,'1h':3600000,'4h':14400000,'24h':86400000};const out={};for(const [k,ms] of Object.entries(windows)){const r=await db.query(`SELECT size,side FROM trades WHERE inst_id=$1 AND ts>=now()-($2 || ' milliseconds')::interval`,[instId,ms]);out[k]={value:cvdDelta(r.rows),sampleSize:r.rows.length};}return out;}
async function anomalies(instId,limit=100){if(!db.isReady())return [];const p=instId?[instId,limit]:[limit];const q=instId?`SELECT id,inst_id symbol,EXTRACT(EPOCH FROM ts)*1000 timestamp,anomaly_type "anomalyType",severity,"measured_value" "measuredValue",baseline,metadata FROM market_anomalies WHERE inst_id=$1 ORDER BY ts DESC LIMIT $2`:`SELECT id,inst_id symbol,EXTRACT(EPOCH FROM ts)*1000 timestamp,anomaly_type "anomalyType",severity,measured_value "measuredValue",baseline,metadata FROM market_anomalies ORDER BY ts DESC LIMIT $1`;return (await db.query(q,p)).rows;}
async function liquidations(instId,limit=100){if(!db.isReady())return [];const r=await db.query(`SELECT EXTRACT(EPOCH FROM ts)*1000 timestamp,side,bk_px "bkPx",size FROM liquidation_events WHERE inst_id=$1 ORDER BY ts DESC LIMIT $2`,[instId,limit]);return r.rows.reverse();}
async function structure(instId){const c=await candles(instId,'5m');if(c.length<2)return {status:'資料不足',structure:'資料不足'};const a=c.at(-2),b=c.at(-1);const o=await oi(instId);const oc=o?.changes?.['5m']?.value;return {status:a&&b&&oc!=null?'正常':'資料不足',structure:classifyStructure(Number(b.close)-Number(a.close),oc),priceChange:pctChange(Number(b.close),Number(a.close)),oiChange:o?.changes?.['5m']||null};}
async function research(instId,limit=100){if(!db.isReady())return {sampleSize:0,status:'資料不足，無法確認',events:[]};const r=await db.query(`SELECT id,anomaly_id "anomalyId",EXTRACT(EPOCH FROM t0)*1000 t0,t5_price "t5Price",t15_price "t15Price",t1h_price "t1hPrice",t4h_price "t4hPrice",t24h_price "t24hPrice",t5_return "t5Return",t15_return "t15Return",t1h_return "t1hReturn",t4h_return "t4hReturn",t24h_return "t24hReturn",mfe,mae,completed_at "completedAt" FROM research_events WHERE inst_id=$1 ORDER BY t0 DESC LIMIT $2`,[instId,limit]);return {sampleSize:r.rows.length,status:r.rows.length?'正常':'資料不足，無法確認',events:r.rows};}
async function rankings(){if(!db.isReady())return {status:'資料不足',oi:[],volume:[],funding:[],liquidation:[]};const [oiR,volR,funR,liqR]=await Promise.all([db.query(`SELECT inst_id symbol,MAX(oi_usd) FILTER(WHERE rn=1) oi,(MAX(oi_usd) FILTER(WHERE rn=1)-MAX(oi_usd) FILTER(WHERE rn=2)) oi_change FROM (SELECT inst_id,oi_usd,ROW_NUMBER() OVER(PARTITION BY inst_id ORDER BY ts DESC) rn FROM open_interest_snapshots WHERE ts>now()-interval '5 minutes')x GROUP BY inst_id ORDER BY oi_change DESC NULLS LAST LIMIT 20`),db.query(`SELECT inst_id symbol,volume,ts FROM (SELECT inst_id,volume,ts,ROW_NUMBER() OVER(PARTITION BY inst_id ORDER BY ts DESC) rn FROM ticker_snapshots)x WHERE rn=1 ORDER BY volume DESC NULLS LAST LIMIT 20`),db.query(`SELECT inst_id symbol,funding_rate "fundingRate",ts FROM (SELECT inst_id,funding_rate,ts,ROW_NUMBER() OVER(PARTITION BY inst_id ORDER BY ts DESC) rn FROM funding_snapshots)x WHERE rn=1 ORDER BY funding_rate DESC NULLS LAST LIMIT 20`),db.query(`SELECT inst_id symbol,COUNT(*) events,SUM(size) size FROM liquidation_events WHERE ts>now()-interval '1 hour' GROUP BY inst_id ORDER BY events DESC,size DESC LIMIT 20`)]);return {status:'正常',oi:oiR.rows,volume:volR.rows,funding:funR.rows,liquidation:liqR.rows};}
module.exports={instruments,tickers,candles,trades,orderBook,funding,fundingHistory,oi,openInterest:async()=>{const rows=await instruments();return Promise.all(rows.map(x=>oi(x.instId)));},cvd,anomalies,liquidations,structure,research,rankings,isUsdtSwap};
