'use strict';
const {TTLCache}=require('./cache');
const okx=require('./okx');
const config=require('./config');
const db=require('./db');
const {normalizeCandle,normalizeTicker,normalizeTrade,normalizeOrderBook,normalizeOI,normalizeFunding,numberOrNull}=require('./normalize');
const {pctChange}=require('./analytics');
const cache=new TTLCache();
function isUsdtSwap(i){return i?.instType==='SWAP'&&i?.state==='live'&&(i?.quoteCcy==='USDT'||i?.settleCcy==='USDT');}
async function instruments(){const hit=cache.get('instruments');if(hit)return hit;const data=(await okx.getInstruments()).filter(isUsdtSwap);if(db.isReady())await db.upsertInstruments(data);return cache.set('instruments',data,config.CACHE_TTL_MS.instruments);}
async function tickers(){const hit=cache.get('tickers');if(hit)return hit;const allowed=new Set((await instruments()).map(x=>x.instId));return cache.set('tickers',(await okx.getTickers()).filter(x=>allowed.has(x.instId)).map(normalizeTicker),config.CACHE_TTL_MS.tickers);}
async function candles(instId,bar='5m'){if(!config.BARS.includes(bar))throw new Error('Unsupported bar');const key=`candles:${instId}:${bar}`,hit=cache.get(key);if(hit)return hit;if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM ts)*1000 timestamp,open,high,low,close,volume,volume_currency "volumeCurrency",volume_quote "volumeQuote",confirmed FROM candles WHERE inst_id=$1 AND bar='5m' ORDER BY ts DESC LIMIT 500`,[instId]);let rows=r.rows.reverse();if(bar!=='5m'){const mins=bar==='15m'?15:bar==='1H'?60:240,bucketMs=mins*60000,m=new Map();for(const x of rows){const k=Math.floor(Number(x.timestamp)/bucketMs)*bucketMs;const a=m.get(k)||{timestamp:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:0,volumeCurrency:0,volumeQuote:0,confirmed:true};a.high=Math.max(Number(a.high),Number(x.high));a.low=Math.min(Number(a.low),Number(x.low));a.close=x.close;a.volume+=Number(x.volume||0);a.volumeCurrency+=Number(x.volumeCurrency||0);a.volumeQuote+=Number(x.volumeQuote||0);a.confirmed=a.confirmed&&Boolean(x.confirmed);m.set(k,a);}rows=[...m.values()];}return cache.set(key,rows,config.CACHE_TTL_MS.candles);}return cache.set(key,(await okx.getCandles(instId,bar)).map(normalizeCandle),config.CACHE_TTL_MS.candles);}
async function trades(instId,limit=100){const n=Math.max(1,Math.min(Number(limit)||100,500)),key=`trades:${instId}:${n}`,hit=cache.get(key);if(hit)return hit;if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM ts)*1000 timestamp,price,size,side,trade_id "tradeId",source FROM trades WHERE inst_id=$1 ORDER BY ts DESC LIMIT $2`,[instId,n]);return cache.set(key,r.rows.reverse(),config.CACHE_TTL_MS.trades);}return cache.set(key,(await okx.getTrades(instId,n)).map(normalizeTrade),config.CACHE_TTL_MS.trades);}
async function orderBook(instId,sz=config.MAX_ORDER_BOOK_LEVELS){const n=Math.max(1,Math.min(Number(sz)||config.MAX_ORDER_BOOK_LEVELS,config.MAX_ORDER_BOOK_LEVELS)),key=`orderbook:${instId}:${n}`,hit=cache.get(key);if(hit)return hit;const raw=(await okx.getOrderBook(instId,n))[0];if(!raw)return null;const bids=raw.bids.map(normalizeOrderBook),asks=raw.asks.map(normalizeOrderBook),bidVolume=bids.reduce((a,x)=>a+(x.volume||0),0),askVolume=asks.reduce((a,x)=>a+(x.volume||0),0),bestBid=bids[0]?.price??null,bestAsk=asks[0]?.price??null,total=bidVolume+askVolume;return cache.set(key,{symbol:instId,bids,asks,bestBid,bestAsk,bidVolume,askVolume,bidAskRatio:askVolume?bidVolume/askVolume:null,spread:bestBid!=null&&bestAsk!=null?bestAsk-bestBid:null,timestamp:numberOrNull(raw.ts),seqId:raw.seqId,warning:'Order Book 為掛單資料，不代表實際成交。'},config.CACHE_TTL_MS.orderBook);}
async function funding(instId){const key=`funding:${instId}`,hit=cache.get(key);if(hit)return hit;if(db.isReady()){const r=await db.query(`SELECT funding_rate "fundingRate",EXTRACT(EPOCH FROM funding_time)*1000 "fundingTime",EXTRACT(EPOCH FROM next_funding_time)*1000 "nextFundingTime",EXTRACT(EPOCH FROM ts)*1000 timestamp FROM funding_snapshots WHERE inst_id=$1 ORDER BY ts DESC LIMIT 1`,[instId]);if(r.rows[0])return cache.set(key,{...r.rows[0],symbol:instId},config.CACHE_TTL_MS.funding);}const d=(await okx.getFundingRate(instId))[0]||null;return cache.set(key,d?normalizeFunding(d,instId):null,config.CACHE_TTL_MS.funding);}
async function fundingHistory(instId,limit=100){const n=Math.max(1,Math.min(Number(limit)||100,100)),key=`funding-history:${instId}:${n}`,hit=cache.get(key);if(hit)return hit;if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM funding_time)*1000 "fundingTime",funding_rate "fundingRate",realized_rate "realizedRate" FROM funding_history WHERE inst_id=$1 ORDER BY funding_time DESC LIMIT $2`,[instId,n]);return cache.set(key,r.rows.reverse(),config.CACHE_TTL_MS.fundingHistory);}return cache.set(key,(await okx.getFundingHistory(instId,n)).map(x=>({symbol:instId,fundingRate:numberOrNull(x.fundingRate),fundingTime:numberOrNull(x.fundingTime),realizedRate:numberOrNull(x.realizedRate),timestamp:numberOrNull(x.ts)})),config.CACHE_TTL_MS.fundingHistory);}
async function oi(instId){const key=`oi:${instId}`,hit=cache.get(key);if(hit)return hit;if(db.isReady()){const r=await db.query(`SELECT EXTRACT(EPOCH FROM ts)*1000 timestamp,oi,oi_ccy "oiCcy",oi_usd "oiUsd" FROM open_interest_snapshots WHERE inst_id=$1 ORDER BY ts DESC LIMIT 500`,[instId]);const rows=r.rows.reverse(),now=Date.now(),at=age=>rows.slice().reverse().find(x=>Number(x.timestamp)<=now-age),cur=rows.at(-1)||null,changes={};for(const [k,ms] of Object.entries({'5m':300000,'15m':900000,'1h':3600000})){const b=at(ms);changes[k]=cur&&b&&Number(b.oiUsd)!==0?{value:Number(cur.oiUsd)-Number(b.oiUsd),pct:pctChange(Number(cur.oiUsd),Number(b.oiUsd)),sampledAt:b.timestamp}:{value:null,pct:null,sampledAt:null};}return cache.set(key,{symbol:instId,current:cur,changes,sampleCount:rows.length,unit:'USD',status:cur?'正常':'資料不足'},config.CACHE_TTL_MS.openInterest);}const data=await okx.getOpenInterest(),x=data.find(v=>v.instId===instId);return cache.set(key,x?{symbol:instId,current:normalizeOI(x),changes:{'5m':{value:null,pct:null,sampledAt:null},'15m':{value:null,pct:null,sampledAt:null},'1h':{value:null,pct:null,sampledAt:null}},sampleCount:1,unit:'USD',status:'資料不足'}:{symbol:instId,current:null,changes:{'5m':{value:null,pct:null,sampledAt:null},'15m':{value:null,pct:null,sampledAt:null},'1h':{value:null,pct:null,sampledAt:null}},sampleCount:0,unit:'USD',status:'資料不足'},config.CACHE_TTL_MS.openInterest);}
async function markets(){const ids=await instruments();if(!db.isReady()){const rows=await tickers();return {count:ids.length,updatedAt:Date.now(),markets:rows,websocket:null,dataStatus:'資料庫尚未啟用'};}const r=await db.query(`SELECT i.inst_id symbol,t.price,t.change_24h "change24h",t.volume,t.volume_contracts "volumeContracts",EXTRACT(EPOCH FROM t.ts)*1000 timestamp,o.oi_usd oi,o.oi_ccy "oiCcy",o.oi oiContracts,o5.oi_usd oi5,o15.oi_usd oi15,o1h.oi_usd oi1h,f.funding_rate funding,EXTRACT(EPOCH FROM f.ts)*1000 funding_ts,EXTRACT(EPOCH FROM f.funding_time)*1000 "fundingTime",EXTRACT(EPOCH FROM f.next_funding_time)*1000 "nextFundingTime" FROM instruments i LEFT JOIN LATERAL(SELECT price,change_24h,volume,volume_contracts,ts FROM ticker_snapshots WHERE inst_id=i.inst_id ORDER BY ts DESC LIMIT 1)t ON true LEFT JOIN LATERAL(SELECT oi_usd,oi_ccy,oi FROM open_interest_snapshots WHERE inst_id=i.inst_id ORDER BY ts DESC LIMIT 1)o ON true LEFT JOIN LATERAL(SELECT oi_usd FROM open_interest_snapshots WHERE inst_id=i.inst_id AND ts<=now()-interval '5 minutes' ORDER BY ts DESC LIMIT 1)o5 ON true LEFT JOIN LATERAL(SELECT oi_usd FROM open_interest_snapshots WHERE inst_id=i.inst_id AND ts<=now()-interval '15 minutes' ORDER BY ts DESC LIMIT 1)o15 ON true LEFT JOIN LATERAL(SELECT oi_usd FROM open_interest_snapshots WHERE inst_id=i.inst_id AND ts<=now()-interval '1 hour' ORDER BY ts DESC LIMIT 1)o1h ON true LEFT JOIN LATERAL(SELECT funding_rate,ts,funding_time,next_funding_time FROM funding_snapshots WHERE inst_id=i.inst_id ORDER BY ts DESC LIMIT 1)f ON true ORDER BY i.inst_id`);const now=Date.now(),staleMs=config.COLLECTOR_STALE_MS;const rows=r.rows.map(x=>{const stale=x.timestamp==null||now-Number(x.timestamp)>staleMs,changes={};for(const [k,b] of [['5m',x.oi5],['15m',x.oi15],['1h',x.oi1h]])changes[k]=x.oi!=null&&b!=null&&Number(b)!==0?{value:Number(x.oi)-Number(b),pct:(Number(x.oi)-Number(b))/Math.abs(Number(b))*100}:null;return {...x,price:stale?null:x.price,change24h:stale?null:x.change24h,volume:stale?null:x.volume,stale,staleMs:stale&&x.timestamp!=null?now-Number(x.timestamp):null,oiUnit:'USD',oiChanges:changes,fundingTime:x.fundingTime??null,nextFundingTime:x.nextFundingTime??null,dataUpdatedAt:x.timestamp};});return {count:rows.length,updatedAt:Date.now(),markets:rows,websocket:null,dataStatus:{staleThresholdMs:staleMs,staleCount:rows.filter(x=>x.stale).length}};}
module.exports={instruments,tickers,markets,candles,trades,orderBook,funding,fundingHistory,oi,isUsdtSwap};
