'use strict';
const express=require('express'),axios=require('axios'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const app=express(),PORT=Number(process.env.PORT||10000),LIVE=String(process.env.LIVE_TRADING||'false').toLowerCase()==='true';
const BASE=String(process.env.OKX_BASE_URL||'https://www.okx.com').replace(/\/$/,''),KEY=String(process.env.OK_ACCESS_KEY||'').trim(),SECRET=String(process.env.OK_ACCESS_SECRET||'').trim(),PASS=String(process.env.OKX_PASSPHRASE||'').trim();
const TG=String(process.env.TELEGRAM_BOT_TOKEN||'').trim().replace(/["']/g,''),CHAT=String(process.env.TELEGRAM_CHAT_ID||'').trim();
const SYMBOLS=String(process.env.PERP_SYMBOLS||'BTC-USDT-SWAP,ETH-USDT-SWAP,SOL-USDT-SWAP').split(',').map(x=>x.trim()).filter(Boolean);
const LOOP=Math.max(15000,Number(process.env.CHECK_INTERVAL||30000));
const RISK=Math.min(.02,Math.max(.01,Number(process.env.RISK_PCT||.01))),LEV=Math.min(5,Math.max(3,Number(process.env.LEVERAGE||3))),RR=Math.min(3,Math.max(2,Number(process.env.RR||2))),MINP=Math.max(.75,Number(process.env.MIN_BAYES||.75));
const PAPER=Number(process.env.PAPER_EQUITY||43),STATE=process.env.PERP_STATE_FILE||path.join(__dirname,'perp-1h-state.json'),COOLDOWN=30*60*1000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),q=o=>Object.entries(o).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v)).join('&');
async function http(c){let e;for(let i=0;i<3;i++)try{return await axios({timeout:15000,...c})}catch(x){e=x;if(i<2)await sleep(400*(i+1))}throw e}
async function pub(ep,p={}){const s=q(p),r=await http({method:'GET',url:BASE+ep+(s?'?'+s:'')});if(!r.data||String(r.data.code)!=='0')throw Error(JSON.stringify(r.data));return Array.isArray(r.data.data)?r.data.data:[]}
function sig(ts,m,r,b){return crypto.createHmac('sha256',SECRET).update(ts+m.toUpperCase()+r+b).digest('base64')}
async function priv(m,r,o,p){if(!KEY||!SECRET||!PASS)throw Error('OKX credentials missing');const s=p?q(p):'',rp=r+(s?'?'+s:''),b=o?JSON.stringify(o):'',ts=new Date().toISOString(),h={'OK-ACCESS-KEY':KEY,'OK-ACCESS-SIGN':sig(ts,m,rp,b),'OK-ACCESS-TIMESTAMP':ts,'OK-ACCESS-PASSPHRASE':PASS,'Content-Type':'application/json'},x=await http({method:m,url:BASE+rp,data:b||undefined,headers:h});if(!x.data||String(x.data.code)!=='0')throw Error(JSON.stringify(x.data));return Array.isArray(x.data.data)?x.data.data:[]}
function fresh(){return{day:new Date().toISOString().slice(0,10),equity:PAPER,pnl:0,losses:0,cooldownUntil:0,position:null,trades:[]}}
let state;try{state=fs.existsSync(STATE)?{...fresh(),...JSON.parse(fs.readFileSync(STATE,'utf8'))}:fresh()}catch{state=fresh()}
function save(){try{fs.writeFileSync(STATE+'.tmp',JSON.stringify(state,null,2));fs.renameSync(STATE+'.tmp',STATE)}catch(e){console.error('[STATE]',e.message)}}
function recalc(){state.pnl=Number(state.trades.reduce((s,t)=>s+Number(t.pnl||0),0).toFixed(4));let n=0;for(let i=state.trades.length-1;i>=0;i--){const p=Number(state.trades[i].pnl||0);if(p<0)n++;else if(p>0)break}state.losses=n;if(!LIVE)state.equity=Math.max(0,PAPER+state.pnl)}
function blocked(){recalc();const now=Date.now();if(state.cooldownUntil&&now<state.cooldownUntil)return true;if(state.cooldownUntil&&now>=state.cooldownUntil)state.cooldownUntil=0;if(state.losses>=3){state.cooldownUntil=now+COOLDOWN;save();return true}if(state.pnl<=-(PAPER*.10)){save();return true}return false}
async function candles(id,bar,limit=120){const a=await pub('/api/v5/market/candles',{instId:id,bar,limit});return a.slice().sort((x,y)=>Number(x[0])-Number(y[0])).filter(x=>String(x[8])==='1')}
async function ticker(id){return(await pub('/api/v5/market/ticker',{instId:id}))[0]||null}
async function inst(id){return(await pub('/api/v5/public/instruments',{instType:'SWAP',instId:id}))[0]||null}
const close=r=>r.map(x=>Number(x[4])).filter(Number.isFinite),mean=a=>a.reduce((s,x)=>s+x,0)/a.length;
function ema(a,n){if(a.length<n)return null;const k=2/(n+1);let e=mean(a.slice(0,n));for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function bayes(rows){const p=close(rows);if(p.length<30)return null;const r=[];for(let i=1;i<p.length;i++)if(p[i]>0&&p[i-1]>0)r.push(Math.log(p[i]/p[i-1]));const up=r.filter(x=>x>0),dn=r.filter(x=>x<=0);if(!up.length||!dn.length)return null;const sd=a=>Math.max(Math.sqrt(mean(a.map(x=>(x-mean(a))**2))),1e-8),x=r[r.length-1],pr=(up.length+1)/(r.length+2),U=mean(up),D=mean(dn),su=sd(up),sdn=sd(dn),pdf=(z,u,s)=>Math.exp(-.5*((z-u)/s)**2)/s,lu=pdf(x,U,su),ld=pdf(x,D,sdn),pu=(lu*pr)/(lu*pr+ld*(1-pr));return{dir:pu>=.5?'LONG':'SHORT',p:pu>=.5?pu:1-pu}}
function trend4h(rows){const c=close(rows);if(c.length<60)return null;const e20=ema(c,20),e50=ema(c,50),last=c.at(-1);return{dir:last>e20&&e20>e50?'LONG':last<e20&&e20<e50?'SHORT':'NONE'}}
function confirm15(rows,d){const c=close(rows),e=ema(c,20),x=c.at(-1);return c.length>=30&&(d==='LONG'?x>e:x<e)}
function entry5(rows,d){const c=close(rows),e9=ema(c,9),e20=ema(c,20),x=c.at(-1),p=c.at(-2);return c.length>=25&&(d==='LONG'?x>e9&&e9>e20&&x>=p:x<e9&&e9<e20&&x<=p)}
function floorStep(x,s){return Number((Math.floor(x/s)*s).toFixed(8))}
async function equity(){if(!LIVE)return state.equity;const d=await priv('GET','/api/v5/account/balance',null,{ccy:'USDT'}),x=d[0]||{};return Number(x.availEq||x.adjEq||x.totalEq||0)}
async function leverage(id,posSide){if(!LIVE)return;await priv('POST','/api/v5/account/set-leverage',{instId:id,lever:String(LEV),mgnMode:'isolated',posSide})}
async function notify(t){if(!TG||!CHAT)return;try{await http({method:'POST',url:`https://api.telegram.org/bot${TG}/sendMessage`,data:{chat_id:CHAT,text:t}})}catch(e){console.error('[TG]',e.message)}}
async function scan(id){const [i,r4,r1,r15,r5,t]=await Promise.all([inst(id),candles(id,'4H'),candles(id,'1H'),candles(id,'15m'),candles(id,'5m'),ticker(id)]);if(!i||!t)return null;const tr=trend4h(r4),b=bayes(r1);if(!tr||tr.dir==='NONE'||!b||b.dir!==tr.dir||b.p<MINP||!confirm15(r15,b.dir)||!entry5(r5,b.dir))return null;const c=close(r1.slice(-15)),atr=mean(c.slice(1).map((x,j)=>Math.abs(x-c[j]))),price=Number(t.last);if(!(atr>0&&price>0))return null;const stop=Math.max(atr*1.2,price*.003),tp=stop*RR,eq=await equity(),risk=eq*RISK,ct=Number(i.ctVal||1),lot=Number(i.lotSz||1),min=Number(i.minSz||lot);let size=floorStep(risk/(stop*ct),lot);if(size<min)size=min;return{inst:i,price,dir:b.dir,p:b.p,stop,tp,size,risk,notional:size*ct*price}}
async function open(c){const posSide=c.dir==='LONG'?'long':'short';await leverage(c.inst.instId,posSide);const side=c.dir==='LONG'?'buy':'sell',body={instId:c.inst.instId,tdMode:'isolated',side,posSide,ordType:'market',sz:String(c.size),clOrdId:`p1h${Date.now().toString(36)}`.slice(0,32)};let entry=c.price;if(LIVE){const r=(await priv('POST','/api/v5/trade/order',body))[0];if(!r||String(r.sCode)!=='0')throw Error('ORDER '+JSON.stringify(r));entry=Number(r.avgPx||entry)}state.position={instId:c.inst.instId,dir:c.dir,entry,size:c.size,stop:c.dir==='LONG'?entry-c.stop:entry+c.stop,tp:c.dir==='LONG'?entry+c.tp:entry-c.tp,risk:c.risk,p:c.p,ctVal:Number(c.inst.ctVal||1),openedAt:new Date().toISOString()};save();await notify(`🟡 PERP 1H ENTRY\n${c.inst.instId}\n${c.dir}\nEntry ${entry}\nSize ${c.size}\n${LEV}x isolated\nRisk ${c.risk.toFixed(4)}U\nSL ${state.position.stop}\nTP ${state.position.tp}\n1H Bayesian ${(c.p*100).toFixed(1)}%\nRR 1:${RR}\n${LIVE?'LIVE':'PAPER'}`);console.log('[ENTRY]',state.position)}
async function close(reason,px){const p=state.position;if(!p)return;let ex=px;if(LIVE){const posSide=p.dir==='LONG'?'long':'short',side=p.dir==='LONG'?'sell':'buy',r=(await priv('POST','/api/v5/trade/order',{instId:p.instId,tdMode:'isolated',side,posSide,ordType:'market',sz:String(p.size),clOrdId:`x1h${Date.now().toString(36)}`.slice(0,32)}))[0];if(!r||String(r.sCode)!=='0')throw Error('CLOSE '+JSON.stringify(r));ex=Number(r.avgPx||ex)}const pnl=(p.dir==='LONG'?ex-p.entry:p.entry-ex)*p.size*p.ctVal;state.trades.push({at:new Date().toISOString(),instId:p.instId,dir:p.dir,entry:p.entry,exit:ex,pnl:Number(pnl.toFixed(4)),reason});state.position=null;recalc();if(state.losses>=3)state.cooldownUntil=Date.now()+COOLDOWN;save();await notify(`${pnl>=0?'🟢':'🔴'} PERP 1H EXIT\n${p.instId}\n${p.dir}\nEntry ${p.entry}\nExit ${ex}\nPnL ${pnl>=0?'+':''}${pnl.toFixed(4)}U\n${reason}\n${LIVE?'LIVE':'PAPER'}`);console.log('[EXIT]',{pnl,reason})}
async function manage(){const p=state.position;if(!p)return;const t=await ticker(p.instId),x=Number(t?.last);if(!(x>0))return;if(p.dir==='LONG'&&(x<=p.stop||x>=p.tp))await close(x<=p.stop?'SL':'TP',x);if(p.dir==='SHORT'&&(x>=p.stop||x<=p.tp))await close(x>=p.stop?'SL':'TP',x)}
async function loop(){try{recalc();if(state.position)return manage();if(blocked())return;for(const s of SYMBOLS){try{const c=await scan(s);if(c){console.log('[SIGNAL]',{instId:s,dir:c.dir,bayesian:+(c.p*100).toFixed(1),risk:+c.risk.toFixed(4),size:c.size,RR});await open(c);break}}catch(e){console.error('[SCAN]',s,e.message)}}}catch(e){console.error('[LOOP]',e.message)}}
app.get('/',(req,res)=>res.json({ok:true,strategy:'4H trend -> 1H Bayesian -> 15M confirm -> 5M entry',mode:LIVE?'LIVE':'PAPER',paperEquity:PAPER,leverage:LEV,riskPct:RISK,rr:RR,position:state.position}));
app.get('/health',(req,res)=>res.json({ok:true,mode:LIVE?'LIVE':'PAPER',paperEquity:PAPER,pnl:state.pnl,losses:state.losses,cooldownUntil:state.cooldownUntil,position:state.position}));
app.listen(PORT,()=>console.log(`[BOOT] OKX 1H PERPETUAL | ${LIVE?'LIVE':'PAPER'} | equity ${PAPER}U | ${LEV}x | risk ${(RISK*100).toFixed(1)}% | RR 1:${RR}`));setTimeout(loop,3000);setInterval(loop,LOOP);
