'use strict';
const fs=require('fs');const path=require('path');const TelegramBot=require('node-telegram-bot-api');
const TOKEN=String(process.env.TELEGRAM_BOT_TOKEN||'').trim().replace(/[\"']/g,'');const ALLOWED_CHAT_ID=String(process.env.TELEGRAM_CHAT_ID||'').trim();const STATE_FILE=process.env.BOT_STATE_FILE||path.join(__dirname,'bot-state.json');
if(!TOKEN){console.log('[TELEGRAM CONTROL] token missing; command receiver disabled');module.exports=null;return;}
const bot=new TelegramBot(TOKEN,{polling:{autoStart:true,params:{timeout:30}}});
function allowed(m){return !ALLOWED_CHAT_ID||String(m.chat.id)===ALLOWED_CHAT_ID;}function load(){try{if(!fs.existsSync(STATE_FILE))return null;return JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));}catch(e){console.error('[TELEGRAM CONTROL] state read:',e.message);return null;}}function n(v,d=4){const x=Number(v||0);return Number.isFinite(x)?x.toFixed(d):'0';}
function statsText(s){if(!s)return'📊 統計\n\n目前還沒有 bot-state.json，尚未建立交易資料。';const t=Array.isArray(s.trades)?s.trades:[],w=t.filter(x=>Number(x.pnl)>0).length,l=t.filter(x=>Number(x.pnl)<0).length,flat=t.filter(x=>Number(x.pnl)===0).length,pnl=t.reduce((a,x)=>a+Number(x.pnl||0),0),wr=t.length?w/t.length*100:0,e=Number(s.paperEquity??20)||0;return['📊 PAPER 統計','',`交易筆數：${t.length}`,`勝場：${w}`,`敗場：${l}`,`平局：${flat}`,`勝率：${wr.toFixed(1)}%`,`累計 PnL：${pnl>=0?'+':''}${n(pnl)}U`,`目前資金：${n(e)}U`,`連敗：${Number(s.consecutiveLosses||0)}`,`冷卻：${Number(s.cooldownUntil||0)>Date.now()?'是':'否'}`,`持倉：${s.position?'有':'無'}`,`策略：1H Bayesian → 5M/15M Event`,`資金配置：Half-Kelly`,`資料檔：${STATE_FILE}`].join('\n');}
function statusText(s){if(!s)return'⚠️ 找不到統計資料檔。';const p=s.position;return['🤖 BOT STATUS','',`模式：${String(process.env.LIVE_TRADING||'false').toLowerCase()==='true'?'LIVE':'PAPER'}`,'1H：Bayesian 大方向','事件：5M / 15M UPDOWN','資金：Half-Kelly',`持倉：${p?`${p.inst?.instId||p.instId||'EVENT'} ${String(p.side||'').toUpperCase()} @ ${n(p.entryPx)}`:'無'}`,`連敗：${Number(s.consecutiveLosses||0)}`,`冷卻：${Number(s.cooldownUntil||0)>Date.now()?'進行中':'無'}`,`交易資料：${Array.isArray(s.trades)?s.trades.length:0} 筆`].join('\n');}
function tradesText(s){const t=Array.isArray(s?.trades)?s.trades.slice(-10).reverse():[];if(!t.length)return'📋 最近交易\n\n目前沒有已完成交易。';const a=['📋 最近 10 筆交易',''];for(const x of t){const p=Number(x.pnl||0);a.push(`${p>=0?'🟢':'🔴'} ${String(x.instId||'').slice(0,42)}`);a.push(`PnL ${p>=0?'+':''}${n(p)}U | ${x.reason||'N/A'} | ${x.at||''}`);}return a.join('\n');}
function help(){return['🤖 OKX EVENT BOT','','/start — 測試 Telegram 回覆','/stats — 查看完整交易統計','/status — 查看機器人狀態','/trades — 查看最近 10 筆已完成交易','/help — 查看指令'].join('\n');}
bot.onText(/^\/(start|help)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,help());});bot.onText(/^\/(stats|stat|統計)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,statsText(load()));});bot.onText(/^\/(status)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,statusText(load()));});bot.onText(/^\/(trades|交易)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,tradesText(load()));});bot.on('polling_error',e=>console.error('[TELEGRAM POLLING]',e?.message||e));bot.getMe().then(me=>console.log(`[TELEGRAM CONTROL] connected @${me.username||me.id}`)).catch(e=>console.error('[TELEGRAM CONTROL] connection failed:',e.message));module.exports=bot;
