'use strict';
const fs=require('fs');const path=require('path');const TelegramBot=require('node-telegram-bot-api');
const TOKEN=String(process.env.TELEGRAM_BOT_TOKEN||'').trim().replace(/[\"']/g,'');const ALLOWED_CHAT_ID=String(process.env.TELEGRAM_CHAT_ID||'').trim();const STATE_FILE=process.env.BOT_STATE_FILE||path.join(__dirname,'bot-state.json');
if(!TOKEN){console.log('[TELEGRAM CONTROL] token missing; command receiver disabled');module.exports=null;return;}
const bot=new TelegramBot(TOKEN,{polling:false});
function freshState(){return{day:new Date().toISOString().slice(0,10),paperEquity:20,realizedPnl:0,consecutiveLosses:0,cooldownUntil:0,halted:false,position:null,trades:[]};}
function ensureState(){try{if(!fs.existsSync(STATE_FILE)){fs.mkdirSync(path.dirname(STATE_FILE),{recursive:true});fs.writeFileSync(STATE_FILE,JSON.stringify(freshState(),null,2));console.log(`[TELEGRAM CONTROL] state initialized ${STATE_FILE}`);}}catch(e){console.error('[TELEGRAM CONTROL] state init:',e.message);}}
function allowed(m){return !ALLOWED_CHAT_ID||String(m.chat.id)===ALLOWED_CHAT_ID;}function load(){ensureState();try{return JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));}catch(e){console.error('[TELEGRAM CONTROL] state read:',e.message);return freshState();}}function n(v,d=4){const x=Number(v||0);return Number.isFinite(x)?x.toFixed(d):'0';}
function statsText(s){const t=Array.isArray(s.trades)?s.trades:[],w=t.filter(x=>Number(x.pnl)>0).length,l=t.filter(x=>Number(x.pnl)<0).length,flat=t.filter(x=>Number(x.pnl)===0).length,pnl=t.reduce((a,x)=>a+Number(x.pnl||0),0),wr=t.length?w/t.length*100:0,e=Number(s.paperEquity??20)||0;return['📊 PERPETUAL 統計','',`交易筆數：${t.length}`,`勝場：${w}`,`敗場：${l}`,`平局：${flat}`,`勝率：${wr.toFixed(1)}%`,`累計 PnL：${pnl>=0?'+':''}${n(pnl)}U`,`PAPER 資金：${n(e)}U`,`連敗：${Number(s.consecutiveLosses||0)}`,`冷卻：${Number(s.cooldownUntil||0)>Date.now()?'是':'否'}`,`持倉：${s.position?'有':'無'}`,`保證金：5U`,`槓桿：3x`,`名目倉位：15U`].join('\n');}
function statusText(s){const p=s.position;return['🤖 PERPETUAL BOT STATUS','',`模式：${String(process.env.LIVE_TRADING||'false').toLowerCase()==='true'?'LIVE':'PAPER'}`,'商品：BTC / ETH / SOL USDT-SWAP','策略：1H Bayesian → 15M + 5M 確認','進場門檻：75%','保證金：5U','槓桿：3x','名目倉位：15U',`TP：${(Number(process.env.PERP_TP_PCT||.024)*100).toFixed(2)}%`,`SL：${(Number(process.env.PERP_SL_PCT||.008)*100).toFixed(2)}%`,`持倉：${p?`${p.instId} ${String(p.direction||'').toUpperCase()} @ ${n(p.entryPx)}`:'無'}`,`連敗：${Number(s.consecutiveLosses||0)}`,`冷卻：${Number(s.cooldownUntil||0)>Date.now()?'進行中':'無'}`,`交易資料：${Array.isArray(s.trades)?s.trades.length:0} 筆`].join('\n');}
function tradesText(s){const t=Array.isArray(s.trades)?s.trades.slice(-10).reverse():[];if(!t.length)return'📋 最近交易\n\n目前沒有已完成交易。';const a=['📋 最近 10 筆交易',''];for(const x of t){const p=Number(x.pnl||0);a.push(`${p>=0?'🟢':'🔴'} ${String(x.instId||'').slice(0,42)}`);a.push(`${String(x.direction||'').toUpperCase()} | PnL ${p>=0?'+':''}${n(p)}U | ${x.reason||'N/A'} | ${x.at||''}`);}return a.join('\n');}
function help(){return['🤖 OKX PERPETUAL BOT','','/start — 測試 Telegram 回覆','/stats — 查看交易統計','/status — 查看機器人狀態','/trades — 查看最近 10 筆已完成交易','/help — 查看指令'].join('\n');}
bot.onText(/^\/(start|help)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,help());});bot.onText(/^\/(stats|stat|統計)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,statsText(load()));});bot.onText(/^\/(status)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,statusText(load()));});bot.onText(/^\/(trades|交易)(?:@[^ ]+)?$/i,async m=>{if(allowed(m))await bot.sendMessage(m.chat.id,tradesText(load()));});
async function startPolling(){try{await bot.deleteWebHook({drop_pending_updates:false});await bot.startPolling({restart:true,params:{timeout:30}});const me=await bot.getMe();console.log(`[TELEGRAM CONTROL] connected @${me.username||me.id}`);console.log('[TELEGRAM CONTROL] polling owner=single');}catch(e){console.error('[TELEGRAM CONTROL] startup failed:',e.message);}}
process.once('SIGTERM',async()=>{try{await bot.stopPolling({cancel:true});}catch(_){}process.exit(0);});process.once('SIGINT',async()=>{try{await bot.stopPolling({cancel:true});}catch(_){}process.exit(0);});
ensureState();startPolling();module.exports=bot;
