'use strict';
const WebSocket=require('ws');
const config=require('./config');
const logger=require('./logger');
class OKXPublicWS{
 constructor(onEvent=()=>{}){this.ws=null;this.timer=null;this.pingTimer=null;this.instIds=[];this.reconnectAttempt=0;this.connected=false;this.subscriptions=new Set();this.unsupported=new Set();this.onEvent=onEvent;this.latest={tickers:new Map(),openInterest:new Map(),funding:new Map(),liquidations:[]};}
 async start(instIds){this.instIds=[...new Set(instIds)];this.reconnectAttempt=0;this.connect();}
 connect(){if(this.ws&&(this.ws.readyState===WebSocket.OPEN||this.ws.readyState===WebSocket.CONNECTING))return;clearTimeout(this.timer);this.ws=new WebSocket(config.OKX_PUBLIC_WS_URL);this.ws.on('open',()=>{this.connected=true;this.reconnectAttempt=0;logger.info('OKX public WebSocket connected');this.subscribe();this.startHeartbeat();});this.ws.on('message',raw=>this.onMessage(raw));this.ws.on('error',e=>logger.error('OKX public WebSocket error',{error:e.message}));this.ws.on('close',()=>{this.connected=false;this.subscriptions.clear();this.stopHeartbeat();this.scheduleReconnect();logger.warn('OKX public WebSocket disconnected');});}
 scheduleReconnect(){clearTimeout(this.timer);const d=Math.min(config.WS_RECONNECT_MAX_MS,config.WS_RECONNECT_BASE_MS*(2**this.reconnectAttempt));this.reconnectAttempt+=1;this.timer=setTimeout(()=>this.connect(),d);}
 startHeartbeat(){this.stopHeartbeat();this.pingTimer=setInterval(()=>{if(this.ws?.readyState===WebSocket.OPEN)this.ws.send('ping');},config.WS_HEARTBEAT_MS);}
 stopHeartbeat(){clearInterval(this.pingTimer);this.pingTimer=null;}
 subscribe(){if(!this.ws||this.ws.readyState!==WebSocket.OPEN)return;const args=[];for(const id of this.instIds){for(const channel of ['tickers','trades','candle5m','open-interest','funding-rate']){if(!this.unsupported.has(`${channel}:${id}`))args.push({channel,instId:id});}}args.push({channel:'liquidation-orders',instType:'SWAP'});for(let i=0;i<args.length;i+=50){const batch=args.slice(i,i+50);const key=JSON.stringify(batch);if(this.subscriptions.has(key))continue;this.ws.send(JSON.stringify({op:'subscribe',args:batch}));this.subscriptions.add(key);}}
 emit(type,data){try{this.onEvent(type,data);}catch(e){logger.error('WebSocket event handler failed',{type,error:e.message});}}
 onMessage(raw){const text=raw.toString();if(text==='ping'){if(this.ws?.readyState===WebSocket.OPEN)this.ws.send('pong');return;}if(text==='pong')return;let msg;try{msg=JSON.parse(text);}catch{return;}if(msg.event==='error'){const detail=String(msg.msg||'');const channel=msg.arg?.channel;const instId=msg.arg?.instId;const match=detail.match(/channel:([^,\s]+),instId:([^\s]+) doesn't exist/i);if(channel&&instId){this.unsupported.add(`${channel}:${instId}`);}else if(match){this.unsupported.add(`${match[1]}:${match[2]}`);}logger.warn('OKX public WebSocket subscription rejected',{code:msg.code,message:detail,channel:channel||match?.[1]||null,instId:instId||match?.[2]||null});return;}if(!msg.data||!msg.arg)return;const ch=msg.arg.channel;if(ch==='tickers'){for(const d of msg.data){this.latest.tickers.set(d.instId,d);this.emit('ticker',d);}}else if(ch==='open-interest'){for(const d of msg.data){this.latest.openInterest.set(d.instId,d);this.emit('open-interest',d);}}else if(ch==='funding-rate'){for(const d of msg.data){this.latest.funding.set(d.instId,d);this.emit('funding-rate',d);}}else if(ch==='trades'){for(const d of msg.data)this.emit('trade',d);}else if(ch==='candle5m'){for(const d of msg.data)this.emit('candle5m',d);}else if(ch==='liquidation-orders'){for(const group of msg.data||[]){for(const detail of group.details||[]){const e={symbol:group.instId,side:detail.side,price:Number(detail.bkPx),size:Number(detail.sz),timestamp:Number(detail.ts),raw:detail};this.latest.liquidations=[e,...this.latest.liquidations].slice(0,500);this.emit('liquidation',e);}}}}
 snapshot(){return {connected:this.connected,subscriptions:this.subscriptions.size,openInterest:Object.fromEntries(this.latest.openInterest),funding:Object.fromEntries(this.latest.funding),liquidations:this.latest.liquidations,tickers:Object.fromEntries(this.latest.tickers)};}
}
module.exports={OKXPublicWS};
